### ISSUE TITLE
How can I use search-products to filter data

### ISSUE THREAD

**Issue by elecoest** [CodyHouse/cd-advanced-filter-changelog#1]
Hello,

On your demo we can find https://codyhouse.co/ds/components/app/advanced-filter.

On the side bar, we have a search input. But it doesn't work...

How can I adapt the code to have this functionnality ?

Thanks

**Comment by elecoest** [comment]
any answer ? Anybody to help me ?

**Comment by claudia-romano** [comment]
Hi there,
we have updated the component to include a custom filtering function for the search input controller:
https://codyhouse.co/ds/components/app/advanced-filter

You can find more info here:
https://codyhouse.co/ds/components/info/advanced-filter#filtering

Cheers!
