### ISSUE TITLE
How implement server filter

### ISSUE THREAD

**Issue by elecoest** [CodyHouse/cd-advanced-filter-changelog#2]
Hi there,

In ma calendar, I've a lot of events
https://www.t2area.com/calendrier.html

I'd like to implement 2 things :
- infinite scroll : add the next page, saving users from a full page load.
- server side filter : on filter events, I reload the data (ajax or other)

Could you help me on the way to use ?

Thanks

**Comment by claudia-romano** [comment]
Hi there,
if you need to make an ajax call, here are the steps you should follow:
https://codyhouse.co/ds/components/info/advanced-filter#custom-filtering

As for the infinite scroll, you can use the Infinite Scroll component:
https://codyhouse.co/ds/components/app/infinite-scroll

Cheers!

**Comment by elecoest** [comment]
Hi,

I know your documentation :)

I need an help to start working with https://codyhouse.co/ds/components/info/advanced-filter#custom-filtering and ajax. Where can I insert my ajax call. And what is the best way to invoque this data reload on each filter's action with each filter's value ?

Many thanks

**Comment by claudia-romano** [comment]
Hi, you do not need to include the ajax call in the component JS file. 

You will need to listen to changes in the `.js-adv-filter__form` form element (e.g., `change` event, `input` event) and use the [FormData interface](https://developer.mozilla.org/en-US/docs/Web/API/FormData) to pass your filter's values to your backend.  Hope this helps.

Cheers!
