### ISSUE TITLE
visual glitch in interaction

### ISSUE THREAD

**Issue by chemix** [CodyHouse/cd-advanced-filter-changelog#3]
Thanks for a great component. I'm using it first time and save me a lot of time. 

There are two screenshots from demo with 2 glitches
- the number input field overflow the grid
- when is no result, tha main space for filter and content is changing

![obrazek](https://user-images.githubusercontent.com/42802/156509713-0a19f67f-d31d-41e2-b6b9-9158c0ca9c36.png)

![obrazek](https://user-images.githubusercontent.com/42802/156509738-51fe8159-84db-4b20-9ef2-9bb171028435.png)

best regards

**Comment by claudia-romano** [comment]
H there,
thanks for the heads-up! We just pushed an updated version that should fix the issue. You can get the updated CSS code here:
https://codyhouse.co/ds/components/app/advanced-filter

Cheers!
