### ISSUE TITLE
Inputs appear on top of custom select dropdown

### ISSUE THREAD

**Issue by schmolzp** [CodyHouse/cd-advanced-filter-changelog#4]
I am in Chrome 111.0.5563.146

This happens on your demo, if you move the custom select list item right after the search input (using devtools) and add several more options, you will notice that inputs from other accordions (when open) will appear on top of the select dropdown list that pops up when the button is clicked. 

I found what's causing this to happen. On the `.accordion__panel element`, there is this property `transform: translateZ(0px);` and once removed, those inputs will appear below the dropdown again. It had created a new stacking context. I went to see if your demo did this because I had the same issue when working on my site. I am not able to share a link to mine though. I have the select dropdowns first and then checkboxes at the bottom which is how I came across this.

Let me know if this doesn't make sense. Thanks!
<img width="364" alt="Screenshot 2023-03-31 at 1 49 46 PM" src="https://user-images.githubusercontent.com/4573987/229193498-f8a3ca11-51a4-4551-864d-8629c533b0de.png">

**Comment by claudia-romano** [comment]
Hi theres, sorry for the late reply. You can fix this adding the classes `position-relative z-index-2` to the `.accordion__item` wrapping the select:
```
<li class="accordion__item position-relative z-index-2 js-accordion__item js-adv-filter__item">
    <!-- ... -->
</li>
```

We'll make sure to push a fix asap. Thanks!
